### ISSUE TITLE
Site link in github about is out of date

### ISSUE THREAD

**Issue by bloycey** [pngwn/svelte-travel-transitions#20]
Hi!

It looks like the site URL is out of date here:

![image](https://user-images.githubusercontent.com/20733264/143002686-cac58b53-3651-4eb9-8250-c69b6ca00fab.png)

and is now https://svelte-travel.pages.dev/ instead.

I've been using this as a reference for a project and panicked for a moment there, but all is fine!

**Comment by pngwn** [comment]
Ops, thanks for that!

**Comment by pngwn** [comment]
fixed!
